export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";
export const REGISTER_USER_PROFILE = "REGISTER_USER_PROFILE";
export const LOGIN_USER_PROFILE = "LOGIN_USER_PROFILE";
